name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -f -s https://pdf-rag-hf.streamlit.app || echo "App might be sleeping, that's okay"
