name: Keep Streamlit App Alive

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
  push:  # Triggers on every push for testing

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -f -s https://pdf-rag-hf.streamlit.app
